### PR TITLE
Responsive Design of The next web

### PR DESCRIPTION
**Pull request by 0prodigy**
Hey, Please review our code and suggest the necessary changes to make this project more professional and authenticated as well as beautiful

**Content**

- Navbar with the toggle button and search button feature (Please click that )
- The first section made up of a grid and we used gradient color to make that more beautiful.
- We used CSS FlexBox in the latest news, deals, and findings sections.
- Fully responsive on mobile devices.

### CODE REVIEW

**Comment by christianotieno** [comment]
## Pull Request under review by Christian Otieno (TSE)

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey @0prodigy & @hillarioh  :wave:
-
You have done a splendid job! :tada: Good job with the toggle button (search button). It has been nicely done. Keep it up.
We, however, do have some few changes to carry out before we proceed (see review comment).
##
## [REQUIRED] - FIX the medium screen breakpoint
Since this is a responsive project, the contents for **medium (screen: min-width around 768px)** are not properly rendered. For the small screen, it is perfect. The main focus was on the medium and large screens.
- Kindly let's improve on the rendering at the medium screen. It should be aligning 3 articles per row in the latest news, latest findings and latest deals sections and 2 respectively in the apps section, just as with the original.
- And then moving down the width gauge, they should start aligning 1 article per row in all sections as from width 722.
- Please make the highlighted changes and submit another review request.
- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Comment by lekegitrepo** [comment]
### Hi @0prodigy and @hillarioh 👏 👏 
### You did a good job implementing most of the requirements in the previous review but you are still missing some part of the requirements.

**_1. As mentioned by the previous reviewer: the apps section should have two articles per row at the medium screen only the last article can be by itself on the row_**

**_2. Try to fix the excessive margin on the right side of the page_** 👇 

excessive margin

**_if you have any doubts or questions contact me on slack._**

### Reviewed by _Temitayo Adeleke._

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
### Status: Require changes

**Comment by 0prodigy** [comment]
We fix the medium screen breakpoint now in medium screen there will be three articles in one row and only two apps container in one row.
We also removed at the extra right margin

**Comment by hillarioh** [comment]
The app section has two articles per row 
image

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

**Review by mikenath223 — CHANGES_REQUESTED** [review]
Hi Team 👋

You've done good on this project.👏👏

However, some changes need to be made before proceeding:

- [ ] Required - Kindly ensure you get the right look of the page at various breakpoints.
Particularly in a tablet screen size, there are differences between yours and the original kindly fix them👇

* The top article section disappears together with the background gradient on a tablet screen and mobile screen also.
**THIS IS YOURS👇**
ice_screenshot_20200408-103538

**THIS IS WHAT IT SHOULD BE**👇
ice_screenshot_20200408-104941

* Also the latest news section just below it contains three elements per row on a tablet screen size.
**THIS IS YOURS👇**
ice_screenshot_20200408-105419

**THIS IS WHAT ITS SUPPOSED TO BE👇**
ice_screenshot_20200408-103329

Kindly fix this.

* The latest funding rounds section also has just three sections on a tablet screen size.
**THIS IS YOURS👇**
ice_screenshot_20200408-103349

**THIS IS THE WAY IT SHOULD BE👇**
ice_screenshot_20200408-105032

* Also the Apps, Gear, Tech and similar rows below it just contains **TWO(2)** elements per row.
**THIS IS YOURS👇**
ice_screenshot_20200408-110119

**THIS IS THE WAY IT SHOULD BE👇**
ice_screenshot_20200408-103434

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by lekegitrepo** [comment]
### Hi Team 👏 
### You have made some improvement on the page. However, check the images below and compare it with your page.

**_1. Latest news_** 👇 

**_your page:_**
image

**_original page:_**
image

**_2. Latest funding round ..._** 👇 
**_your page:_**
image

**_original page:_**
image

**_3. The section below latest funding round_**  👇 

**_your page:_**
image

**_original page:_**
image

**_4. Latest deals_** 👇 

**_your page:_**
image

**_original page:_**
image

**_Try to align the content in each section appropriately._**

**_if you have any doubts or questions contact me on slack._**

### Reviewed by _Temitayo Adeleke_.

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
#### Status: Require changes

**Comment by thsvr** [comment]
### **STATUS: PROJECT APPROVED** :+1: :+1: 

Hi @0prodigy and @hillarioh :smile: :smile: 

You guys have been doing a hard work to make this project looks professional, congrats for it! :muscle: :muscle: 
You guys fixed the issue mentioned by Temitayo and now your project was approved :fireworks: :fireworks: 


If you have any questions, don't hesitate to contact me through slack [@thaís Vieira Azevedo](url)


### **Happy coding and good luck on the next project** :computer: :computer: 

_Project reviewed by Thaís Vieira (TSE)_

**Pull request merged**
